### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by WangXiZhu** [Waydrow/My-Blog#1]
博主，你好
  你的 config.yml中
    deploy:
        type: git
        repository: git@github.com:Waydrow/My-Blog.git
对应的是travis.yml编译HEXO的目标目录，为什么没有对你的MY-BLOG repo重写呢？

**Comment by Waydrow** [comment]
你是说的我的源代码吗 ?
是这样的，我是在`My-Blog`里开了两个分支，master和gh-pages,
我在本地写完博客之后，`git push`到master分支，触发travis构建，生成的内容放在gh-pages分支

**Comment by WangXiZhu** [comment]
酱紫啊，难怪涉及到权限问题！我还想把编译的文件放到另一个repo里。。可能是这个原因。那你是在https://travis-ci.org中配置的解析到gh-pages下吗？hexo里面_config.yml下 deply配置项 branch没有设置？

**Comment by Waydrow** [comment]
不需要设置的，travis网站中只能选择repo, 不可以选择分支的。
而且本身在master分支里执行`hexo deploy`时，生成的静态博客默认就会放到gh-pages里。
两个仓也可以的，但是设置起来要注意路径。

**Comment by WangXiZhu** [comment]
就是由于分支的问题，搞了好久

**Comment by Waydrow** [comment]
我当初也捣腾了好久，慢慢来。加油

**Comment by WangXiZhu** [comment]
博主你好

现在theme设置为landscape编译能过，但是没有样式。设置为yilla直接没样式。但是我看travis里面的编译过程和就是之前hexo编译一样的。
结果如下
  
         The command "hexo clean" exited with 0.
         3.20s$ hexo g
         INFO  Start processing
         INFO  Files loaded in 1.08 s 
         WARN  No layout: 404.html    //貌似是主题找不到

有空提示提示，哈哈 谢谢~~~

**Comment by WangXiZhu** [comment]
目前配置主题为landscape是可以的，就是YILLA有点问题。明天再继续看看，不过谢谢博主的文章和回答！

**Comment by Waydrow** [comment]
不好意思，没有看到，回复晚了。
上面那个没有样式的问题我好像在stackoverflow上看到过，那上面解决方法是 hexo g 重复执行两次。你可以试一试

**Comment by WangXiZhu** [comment]
恩，好的  3Q
